apiVersion: v1
kind: Service
metadata:
  name: node-web-app
  labels:
    run: node-web-app
spec:
  type: NodePort   # Service type
  ports:
    - nodePort: 30000
      port: 8080
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: node-web-app
  type: LoadBalancer
  externalIPs:
    - 15.168.14.190